on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    tags:
      - v*
    types:
      - completed

name: Create Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          path: './dist/analyzing/*'
          filename: 'analyzing.zip'
      - run: echo $env:GITHUB_REF_NAME > ./version.txt
      - name: Add version file
        uses: actions/upload-artifact@v3
        with:
          name: version
          path: "./version.txt"
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "analyzing.zip,version.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
